### ISSUE TITLE
cy.getReact() returns Error: Component not found

### ISSUE THREAD

**Issue by jamesl1001** [abhinaba-ghosh/cypress-react-selector#57]
Hi Abhinaba,

I'm trying to read the value of a prop from a component using:

`cy.getReact('HomeWelcome').getCurrentState()`

When I run it I get the following error in Cypress:

```
Error: Component not found **<HomeWelcome>**

  There can be multiple reasons for it.

  > Check the root is defined as a env parameter (cypress.json config file).

  > If the root is defined correctly, check other parameters - component name, props and state objects
```

My `cypress.json` looks like so:

```
{ 
    "chromeWebSecurity": false,
    "env": {
        "cypress-react-selector": {
            "root": "#root"
        }
    }
}
```

And after reading some other issues and your readme, I tried to add `cy.waitForReact()` to the `before()` but then I get the following error:

```
TypeError: require.resolve is not a function

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: 'Home'
```

Some other things to note:
- `HomeWelcome` is a nested component
- Redux provider wraps the app
- We're using `BrowserRouter` with `Async react-code-splitting`

Any ideas?

**Comment by abhinaba-ghosh** [comment]
Hi, `cy.waitForReact()` should be executed successfully before proceeding with it. any other `react-selector` commands. This is appearing because of a recent change, can you try the version `2.0.4`?

```
npm i --save-dev cypress-react-selector@2.0.4
```

Let me know that resolves your issue.

**Comment by aditya-3008** [comment]
Hi Abhinaba,

I am also getting same error, while inspecting Component using React-Dev tool. Multiple reasons error. 

 cy.waitForReact();
      const btn = cy.react('Anonymous*', { props: { name: 'abc' } });
       //const btn = cy.react('CatalogGridItem*', { props: { name: 'xyz' } });
      btn.click();

I am writing End to end tests and doesn't have access to source code, so is there any way to get the component name from React dev tool which I can use in my test scripts using Cyrpess-react-selector.

**Comment by abhinaba-ghosh** [comment]
Hi @aditya-3008 , the error you are receiving because the component is not found. If you are sure that you are mentioning the `react-root` correctly in the [configuration file](https://github.com/abhinaba-ghosh/cypress-react-selector#wait-for-application-to-be-ready-to-run-tests), then the only reason is an exact match with the `props` is not found. It is like any other selection process. If you can provide a similar repository where I can reproduce the bug, it will be helpful. You don't need to have the access to the source code, but you need to know what the `react-toot` of the application. If the root is explicitly not provided, then `cypress-react`selector` automatically figure it out. Now, the problem is there can be multiple roots. In that case, you need to provide the target one. 
For a zoom jam, connect me [here](askabhinaba@gmail.com)

**Comment by abhinaba-ghosh** [comment]
Hi @jamesl1001 , use the cypress version `2.0.4`. It should resolve your issue with the same code.

**Comment by jamesl1001** [comment]
Yep, 2.0.4 is working, thanks.

**Comment by abhinaba-ghosh** [comment]
Hey @jamesl1001 I am happy that it is working now. if this library making an impact on your development, you can consider [supporting](https://www.paypal.com/paypalme/abhinabaghosh) the project.
